feat: remove line element from scatter controller default config
thabarbados/Chart.js pull request #2
Opened 2022-06-16 13:17 UTC by thabarbados

2022-06-20 06:36 UTC, dangreen requested changes

2022-06-20 06:36 UTC, dangreen commented on src/core/core.controller.js
> +        if (type === 'scatter' && dataset.showLine) {
Base class shouldn't know about child types.

2022-06-21 10:11 UTC, thabarbados commented on src/core/core.controller.js
> +        if (type === 'scatter' && dataset.showLine) {
fixed

2022-06-21 17:53 UTC, dangreen commented on src/controllers/controller.scatter.js
> +  update(mode) {
@thabarbados  Is this code copypasted from LineController?

2022-06-21 17:54 UTC, dangreen commented on src/controllers/controller.scatter.js
> +  update(mode) {
If there is common code with LineController, maybe then move some to a common file with utils?  To dedupe code.

2022-06-22 09:11 UTC, thabarbados commented on src/controllers/controller.scatter.js
> +  update(mode) {
@dangreen Yes, the source of this method is the LineController, but this is not a copy-paste. 
This code was copied from the LineController and modified for ScatterController.

2022-06-23 09:38 UTC, dangreen approved these changes

2022-06-23 11:54 UTC, closed without merging